version: "3.9"

services:
  client:
    build: ./
    ports:
      - 4321:4321
    volumes:
      - ./:/app
      - /app/node_modules

  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - 4444:4444
    volumes:
      - ./server:/app
      - /app/node_modules
